## Base Goal - Quantitative momentum analysis of precentage change in stock price to prdict fututre trends
api- iex cloud

## Final goal- For NSE

Libraries required->

In [2]:
import numpy as np #The Numpy numerical computing library
import pandas as pd #The Pandas data science library
import requests #The requests library for HTTP requests in Python
import xlsxwriter #The XlsxWriter libarary for 
import math #The Python math module
from scipy import stats #The SciPy stats module

## Api keys

In [3]:
from keys import key_iex
from create_batches import create_batches

In [4]:
cs=requests.get(f"https://api.iex.cloud/v1/data/CORE/ADVANCED_STATS/MSFT?token={key_iex}").json()[0]
cs

{'beta': 1.2012020134406927,
 'totalCash': 143951000000,
 'currentDebt': 124792000000,
 'revenue': 218310000000,
 'grossProfit': 151597000000,
 'totalRevenue': 218310000000,
 'EBITDA': 108892000000,
 'revenuePerShare': 29.37,
 'revenuePerEmployee': 1311368.07,
 'debtToEquity': 2.019740478628451,
 'profitMargin': 0.35314919151665064,
 'enterpriseValue': 2660765471490,
 'enterpriseValueToRevenue': 12.19,
 'priceToSales': 12.52,
 'priceToBook': 12.38,
 'forwardPERatio': 34.19715513990711,
 'pegRatio': 3.1490535803304502,
 'peHigh': 12.105627950004363,
 'peLow': 7.98428448098325,
 'week52highDate': '2023-11-29',
 'week52lowDate': '2023-01-09',
 'putCallRatio': 0.7214398525927875,
 'companyName': 'Microsoft Corporation',
 'marketcap': 2733214471490,
 'week52high': 384.3,
 'week52low': 223.97,
 'week52highSplitAdjustOnly': 384.3,
 'week52highDateSplitAdjustOnly': '2023-11-29',
 'week52lowSplitAdjustOnly': 226.41,
 'week52lowDateSplitAdjustOnly': '2023-01-09',
 'week52change': 0.6527963606570197,
 'sharesOutstanding': 7432262329,
 'float': None,
 'avg10Volume': 20551004,
 'avg30Volume': 25255782,
 'day200MovingAvg': 342.28,
 'day50MovingAvg': 373.55,
 'employees': 221000,
 'ttmEPS': 10.33,
 'ttmDividendRate': 2.777410592316917,
 'dividendYield': 0.007552442127306368,
 'nextDividendDate': '2024-02-14',
 'exDividendDate': '',
 'nextEarningsDate': '2024-01-23',
 'peRatio': 35.45209182693979,
 'maxChangePercent': 15.64772907320474,
 'year5ChangePercent': 2.807073755260284,
 'year2ChangePercent': 0.1860638226506424,
 'year1ChangePercent': 0.6722750215997453,
 'ytdChangePercent': -0.022045527071588134,
 'month6ChangePercent': 0.09426509870107536,
 'month3ChangePercent': 0.15619966680070507,
 'month1ChangePercent': -0.012804681627831991,
 'day30ChangePercent': -0.00284707158351416,
 'day5ChangePercent': -0.022045527071588134}

## External csv

In [5]:
sp500=pd.read_csv('sp_500_stocks.csv')
stock_prices=pd.read_csv('stock_prices.csv')
stock_prices

    Ticker   Price  Market Capitalization  Number Of Shares to Buy
0        A  131.00           3.838354e+10                      151
1      AAL   13.09           8.554846e+09                     1512
2      AAP   60.49           3.599275e+09                      327
3     AAPL  181.91           2.829201e+12                      108
4     ABBV  161.46           2.906280e+11                      122
..     ...     ...                    ...                      ...
500    YUM  128.69           3.607286e+10                      153
501    ZBH  120.20           2.511948e+10                      164
502   ZBRA  252.97           1.299244e+10                       78
503   ZION   42.64           6.317065e+09                      464
504    ZTS  194.04           8.908642e+10                      102

[505 rows x 4 columns]

## Creating dataframe for conserning values

In [6]:
cols=['Ticker', 'Price','One-Year Price Return', 'Number Of Shares to Buy']
stock_param=pd.DataFrame(columns=cols )

Creating batches for faster api requests

In [7]:
batch_req=[]
res=list(create_batches(sp500['Ticker'],100))
for i in res:
    batch_req.append(','.join(i))
print(batch_req)

['A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADSK,AEE,AEP,AES,AFL,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL,ALLE,ALXN,AMAT,AMCR,AMD,AME,AMGN,AMP,AMT,AMZN,ANET,ANSS,ANTM,AON,AOS,APA,APD,APH,APTV,ARE,ATO,ATVI,AVB,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BF.B,BIIB,BIO,BK,BKNG,BKR,BLK,BLL,BMY,BR,BRK.B,BSX,BWA,BXP,C,CAG,CAH,CARR,CAT,CB,CBOE,CBRE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CFG,CHD,CHRW,CHTR,CI,CINF,CL,CLX,CMA,CMCSA', 'CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRT,CRM,CSCO,CSX,CTAS,CTL,CTSH,CTVA,CTXS,CVS,CVX,CXO,D,DAL,DD,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISCK,DISH,DLR,DLTR,DOV,DOW,DPZ,DRE,DRI,DTE,DUK,DVA,DVN,DXC,DXCM,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,ES,ESS,ETFC,ETN,ETR,EVRG,EW,EXC,EXPD,EXPE,EXR,F,FANG,FAST,FB,FBHS,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FLIR,FLS,FLT,FMC,FOX,FOXA,FRC,FRT,FTI,FTNT,FTV,GD,GE,GILD', 'GIS,GL,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HFC,HIG,HII,HLT,HOLX,HON,HPE,HPQ,HRB,HRL,HSIC,HST,HSY,HUM,HWM,IBM,ICE,IDXX,IEX,IFF,ILMN,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IQV,IR,IRM,ISRG,IT,ITW,IVZ,J,JBHT,JCI,JKHY,JNJ,JNPR,JPM,K,KEY,KEYS,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LB,LDOS,LEG,LEN,LH,LHX,LIN,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LW,LYB,LYV,MA,MAA,MAR,MAS,MCD,MCHP', 'MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MKTX,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSCI,MSFT,MSI,MTB,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLOK,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTRS,NUE,NVDA,NVR,NWL,NWS,NWSA,O,ODFL,OKE,OMC,ORCL,ORLY,OTIS,OXY,PAYC,PAYX,PBCT,PCAR,PEAK,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PXD,PYPL,QCOM,QRVO,RCL,RE,REG,REGN,RF,RHI,RJF,RL,RMD,ROK', 'ROL,ROP,ROST,RSG,RTX,SBAC,SBUX,SCHW,SEE,SHW,SIVB,SJM,SLB,SLG,SNA,SNPS,SO,SPG,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TDG,TDY,TEL,TFC,TFX,TGT,TIF,TJX,TMO,TMUS,TPR,TROW,TRV,TSCO,TSN,TT,TTWO,TWTR,TXN,TXT,TYL,UA,UAA,UAL,UDR,UHS,ULTA,UNH,UNM,UNP,UPS,URI,USB,V,VAR,VFC,VIAC,VLO,VMC,VNO,VRSK,VRSN,VRTX,VTR,VZ,WAB,WAT,WBA,WDC,WEC,WELL,WFC,WHR,WLTW,WM,WMB,WMT,WRB,WRK,WST,WU,WY,WYNN,XEL,XLNX,XOM,XRAY,XRX,XYL', 'YUM,ZBH,ZBRA,ZION,ZTS']

In [8]:
#updated way
for symbol in batch_req:
    ot=requests.get(f"https://api.iex.cloud/v1/data/CORE/ADVANCED_STATS/{symbol}?token={key_iex}").json()
    sym=symbol.split(',')
    #print(sym)
    for i in range(0,len(ot)):
        cs=ot[i]
        stock_param.loc[len(stock_param.index)] = [sym[i], 
                                                    stock_prices.loc[len(stock_param.index),'Price'], 
                                                    cs["year1ChangePercent"], 
                                                    'N/A']

In [9]:
stock_param

    Ticker   Price One-Year Price Return Number Of Shares to Buy
0        A  131.00             -0.135438                     N/A
1      AAL   13.09             -0.027877                     N/A
2      AAP   60.49             -0.589858                     N/A
3     AAPL  181.91              0.461199                     N/A
4     ABBV  161.46              0.031807                     N/A
..     ...     ...                   ...                     ...
500    YUM  128.69              0.023922                     N/A
501    ZBH  120.20             -0.040998                     N/A
502   ZBRA  252.97              -0.02834                     N/A
503   ZION   42.64              -0.06271                     N/A
504    ZTS  194.04              0.351856                     N/A

[505 rows x 4 columns]

Sorting these values according to yearlly return to find to 50 with best return

In [10]:
stock_param.sort_values('One-Year Price Return',ascending=False,inplace=True)

In [13]:

super50=stock_param[:50]

super50

    Ticker    Price One-Year Price Return Number Of Shares to Buy
345   NVDA   479.98              2.443309                     N/A
275     LB    79.92              2.281287                     N/A
390    RCL   119.00              1.297677                     N/A
31     AMD   136.01              1.223327                     N/A
370    PHM   100.31              1.148093                     N/A
37    ANET   230.56              1.109051                     N/A
50    AVGO  1049.01               0.95279                     N/A
84     CCL    16.85              0.936313                     N/A
208    GPS    20.12               0.92114                     N/A
339    NOW   671.87              0.845818                     N/A
114    CRM   251.24              0.841866                     N/A
288   LRCX   731.08              0.792681                     N/A
198     GE   124.66              0.776843                     N/A
242   INTC    46.87              0.760274                     N/A
36    AMZN   144.57              0.747353                     N/A
283    LLY   614.50              0.740363                     N/A
9     ADBE   567.05              0.719035                     N/A
340    NRG    51.29              0.698321                     N/A
194    FTI    19.56              0.686354                     N/A
320   MSFT   367.94              0.672275                     N/A
132    DHI   147.69              0.625004                     N/A
101    CMG  2220.47              0.622097                     N/A
422    STX    80.77              0.611896                     N/A
85    CDNS   255.92              0.611671                     N/A
431    TDG   975.53              0.594115                     N/A
65    BKNG  3419.94              0.588921                     N/A
243   INTU   586.82              0.585051                     N/A
204   GOOG   138.04              0.583381                     N/A
278    LEN   145.07              0.580892                     N/A
205  GOOGL   136.39              0.574594                     N/A
172   EXPE   144.82              0.573333                     N/A
465    VAR   177.07              0.571162                     N/A
361   PCAR    93.78              0.564969                     N/A
188    FLT   280.88              0.557528                     N/A
324     MU    82.71              0.546522                     N/A
369     PH   452.06              0.545448                     N/A
110   COST   648.35              0.544696                     N/A
29    AMAT   149.31               0.54239                     N/A
211    GWW   815.98              0.539008                     N/A
415   SNPS   490.18              0.538884                     N/A
113   CPRT    46.64              0.537572                     N/A
332   NFLX   474.67              0.530707                     N/A
384    PVH   117.25              0.525426                     N/A
166    ETN   234.48              0.521151                     N/A
296    MAR   220.02              0.513506                     N/A
376    PNR    68.93              0.511195                     N/A
462    URI   548.86              0.507997                     N/A
273    KSU   293.59              0.506512                     N/A
70      BR   197.09              0.503377                     N/A
346    NVR  6912.71              0.495356                     N/A

In [14]:
super50.reset_index(inplace=True)

    index Ticker    Price One-Year Price Return Number Of Shares to Buy
0     345   NVDA   479.98              2.443309                     N/A
1     275     LB    79.92              2.281287                     N/A
2     390    RCL   119.00              1.297677                     N/A
3      31    AMD   136.01              1.223327                     N/A
4     370    PHM   100.31              1.148093                     N/A
5      37   ANET   230.56              1.109051                     N/A
6      50   AVGO  1049.01               0.95279                     N/A
7      84    CCL    16.85              0.936313                     N/A
8     208    GPS    20.12               0.92114                     N/A
9     339    NOW   671.87              0.845818                     N/A
10    114    CRM   251.24              0.841866                     N/A
11    288   LRCX   731.08              0.792681                     N/A
12    198     GE   124.66              0.776843                     N/A
13    242   INTC    46.87              0.760274                     N/A
14     36   AMZN   144.57              0.747353                     N/A
15    283    LLY   614.50              0.740363                     N/A
16      9   ADBE   567.05              0.719035                     N/A
17    340    NRG    51.29              0.698321                     N/A
18    194    FTI    19.56              0.686354                     N/A
19    320   MSFT   367.94              0.672275                     N/A
20    132    DHI   147.69              0.625004                     N/A
21    101    CMG  2220.47              0.622097                     N/A
22    422    STX    80.77              0.611896                     N/A
23     85   CDNS   255.92              0.611671                     N/A
24    431    TDG   975.53              0.594115                     N/A
25     65   BKNG  3419.94              0.588921                     N/A
26    243   INTU   586.82              0.585051                     N/A
27    204   GOOG   138.04              0.583381                     N/A
28    278    LEN   145.07              0.580892                     N/A
29    205  GOOGL   136.39              0.574594                     N/A
30    172   EXPE   144.82              0.573333                     N/A
31    465    VAR   177.07              0.571162                     N/A
32    361   PCAR    93.78              0.564969                     N/A
33    188    FLT   280.88              0.557528                     N/A
34    324     MU    82.71              0.546522                     N/A
35    369     PH   452.06              0.545448                     N/A
36    110   COST   648.35              0.544696                     N/A
37     29   AMAT   149.31               0.54239                     N/A
38    211    GWW   815.98              0.539008                     N/A
39    415   SNPS   490.18              0.538884                     N/A
40    113   CPRT    46.64              0.537572                     N/A
41    332   NFLX   474.67              0.530707                     N/A
42    384    PVH   117.25              0.525426                     N/A
43    166    ETN   234.48              0.521151                     N/A
44    296    MAR   220.02              0.513506                     N/A
45    376    PNR    68.93              0.511195                     N/A
46    462    URI   548.86              0.507997                     N/A
47    273    KSU   293.59              0.506512                     N/A
48     70     BR   197.09              0.503377                     N/A
49    346    NVR  6912.71              0.495356                     N/A

In [18]:
super50=super50.drop('index',axis=1)

In [19]:
super50

   Ticker    Price One-Year Price Return Number Of Shares to Buy
0    NVDA   479.98              2.443309                     N/A
1      LB    79.92              2.281287                     N/A
2     RCL   119.00              1.297677                     N/A
3     AMD   136.01              1.223327                     N/A
4     PHM   100.31              1.148093                     N/A
5    ANET   230.56              1.109051                     N/A
6    AVGO  1049.01               0.95279                     N/A
7     CCL    16.85              0.936313                     N/A
8     GPS    20.12               0.92114                     N/A
9     NOW   671.87              0.845818                     N/A
10    CRM   251.24              0.841866                     N/A
11   LRCX   731.08              0.792681                     N/A
12     GE   124.66              0.776843                     N/A
13   INTC    46.87              0.760274                     N/A
14   AMZN   144.57              0.747353                     N/A
15    LLY   614.50              0.740363                     N/A
16   ADBE   567.05              0.719035                     N/A
17    NRG    51.29              0.698321                     N/A
18    FTI    19.56              0.686354                     N/A
19   MSFT   367.94              0.672275                     N/A
20    DHI   147.69              0.625004                     N/A
21    CMG  2220.47              0.622097                     N/A
22    STX    80.77              0.611896                     N/A
23   CDNS   255.92              0.611671                     N/A
24    TDG   975.53              0.594115                     N/A
25   BKNG  3419.94              0.588921                     N/A
26   INTU   586.82              0.585051                     N/A
27   GOOG   138.04              0.583381                     N/A
28    LEN   145.07              0.580892                     N/A
29  GOOGL   136.39              0.574594                     N/A
30   EXPE   144.82              0.573333                     N/A
31    VAR   177.07              0.571162                     N/A
32   PCAR    93.78              0.564969                     N/A
33    FLT   280.88              0.557528                     N/A
34     MU    82.71              0.546522                     N/A
35     PH   452.06              0.545448                     N/A
36   COST   648.35              0.544696                     N/A
37   AMAT   149.31               0.54239                     N/A
38    GWW   815.98              0.539008                     N/A
39   SNPS   490.18              0.538884                     N/A
40   CPRT    46.64              0.537572                     N/A
41   NFLX   474.67              0.530707                     N/A
42    PVH   117.25              0.525426                     N/A
43    ETN   234.48              0.521151                     N/A
44    MAR   220.02              0.513506                     N/A
45    PNR    68.93              0.511195                     N/A
46    URI   548.86              0.507997                     N/A
47    KSU   293.59              0.506512                     N/A
48     BR   197.09              0.503377                     N/A
49    NVR  6912.71              0.495356                     N/A

Now lets distribute the money in these stocks according to the  return ratio

In [20]:
su=super50['One-Year Price Return'].sum()
print(su)

37.24853188457307

Lets invest total value of 10000000

In [23]:
super50.info()
super50['One-Year Price Return']=pd.to_numeric(super50['One-Year Price Return'])
super50.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Ticker                   50 non-null     object
 1   Price                    50 non-null     float64
 2   One-Year Price Return    50 non-null     float64
 3   Number Of Shares to Buy  50 non-null     object
dtypes: float64(2), object(2)
memory usage: 1.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Ticker                   50 non-null     object
 1   Price                    50 non-null     float64
 2   One-Year Price Return    50 non-null     float64
 3   Number Of Shares to Buy  50 non-null     object
dtypes: float64(2), object(2)
memory usage: 1.7+ KB

In [24]:
for i in range (0,50):
    super50.loc[i,'Number Of Shares to Buy']=math.floor(((super50.loc[i,'One-Year Price Return']/su)*10000000)/ super50.loc[i,'Price'])
super50

   Ticker    Price  One-Year Price Return Number Of Shares to Buy
0    NVDA   479.98               2.443309                    1366
1      LB    79.92               2.281287                    7663
2     RCL   119.00               1.297677                    2927
3     AMD   136.01               1.223327                    2414
4     PHM   100.31               1.148093                    3072
5    ANET   230.56               1.109051                    1291
6    AVGO  1049.01               0.952790                     243
7     CCL    16.85               0.936313                   14918
8     GPS    20.12               0.921140                   12291
9     NOW   671.87               0.845818                     337
10    CRM   251.24               0.841866                     899
11   LRCX   731.08               0.792681                     291
12     GE   124.66               0.776843                    1673
13   INTC    46.87               0.760274                    4354
14   AMZN   144.57               0.747353                    1387
15    LLY   614.50               0.740363                     323
16   ADBE   567.05               0.719035                     340
17    NRG    51.29               0.698321                    3655
18    FTI    19.56               0.686354                    9420
19   MSFT   367.94               0.672275                     490
20    DHI   147.69               0.625004                    1136
21    CMG  2220.47               0.622097                      75
22    STX    80.77               0.611896                    2033
23   CDNS   255.92               0.611671                     641
24    TDG   975.53               0.594115                     163
25   BKNG  3419.94               0.588921                      46
26   INTU   586.82               0.585051                     267
27   GOOG   138.04               0.583381                    1134
28    LEN   145.07               0.580892                    1075
29  GOOGL   136.39               0.574594                    1131
30   EXPE   144.82               0.573333                    1062
31    VAR   177.07               0.571162                     865
32   PCAR    93.78               0.564969                    1617
33    FLT   280.88               0.557528                     532
34     MU    82.71               0.546522                    1773
35     PH   452.06               0.545448                     323
36   COST   648.35               0.544696                     225
37   AMAT   149.31               0.542390                     975
38    GWW   815.98               0.539008                     177
39   SNPS   490.18               0.538884                     295
40   CPRT    46.64               0.537572                    3094
41   NFLX   474.67               0.530707                     300
42    PVH   117.25               0.525426                    1203
43    ETN   234.48               0.521151                     596
44    MAR   220.02               0.513506                     626
45    PNR    68.93               0.511195                    1990
46    URI   548.86               0.507997                     248
47    KSU   293.59               0.506512                     463
48     BR   197.09               0.503377                     685
49    NVR  6912.71               0.495356                      19